# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  www.typist.tech:
    site_hosts:
      - canonical: staging.typist.tech
        # redirects:
        #   - otherdomain.com
    local_path: ../bedrock # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:tangrufus/www-typist-tech-bedrock.git # replace with your Git repo URL
    # repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: "{{ site_version | default('master') }}"
    multisite:
      enabled: false
    ssl:
      enabled: true
      stapling_enabled: false
      provider: cloudflare-origin-ca
      client_cert_url: 'https://support.cloudflare.com/hc/en-us/article_attachments/201243967/origin-pull-ca.pem'
    cloudflare_origin_ca:
      hostnames:
        - '*.typist.tech'
    cache:
      enabled: true
